#!/bin/bash
setenforce 0
  sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

 sudo yum update -y
 sudo amazon-linux-extras install docker -y
 systemctl enable docker
 systemctl daemon-reload && systemctl restart docker 
 sudo usermod -a -G docker ec2-user

cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF 

yum install -y kubelet-1.21.2
yum install -y kubectl-1.21.2
yum install -y kubeadm-1.21.2 


systemctl daemon-reload 
systemctl restart kubelet
 
systemctl  status kubelet

systemctl enable  kubelet
